name: Build Docker Image
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build and (on tag) push Docker images
    runs-on: ubuntu-latest
    env:
      IMAGE: virajsh/uniclare-client
    steps:
      - uses: actions/checkout@v3

      - name: Show git info
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=${GITHUB_REF##*/}"
          git --no-pager log -1 --pretty=oneline

      - name: Install Python
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Hash JS/CSS Assets
        run: |
          cd app/static
          python3 hash.py hash

      - name: Build latest image
        run: |
          docker build . -f Dockerfile -t $IMAGE:latest

      - name: Build versioned image (only for tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME=${GITHUB_REF##refs/tags/}
          docker build . -f Dockerfile -t $IMAGE:${TAG_NAME}

      - name: Login to Docker Hub (only for tag)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Push versioned image (only for tag) - push version first
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME=${GITHUB_REF##refs/tags/}
          docker push $IMAGE:${TAG_NAME}

      - name: Push latest image (only for tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push $IMAGE:latest